<a href="https://colab.research.google.com/github/keuperj/einsum/blob/main/torch_einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### Linear Combination of three input to on output channel

In [2]:
A = torch.ones((5,5))
B = 2*A
C = 4*A

In [3]:
H=torch.stack([A, B, C])

In [4]:
H.shape

torch.Size([3, 5, 5])

In [5]:
a=torch.tensor([1.0,2.0,3.0])

In [6]:
%%timeit
a[0]*A+a[1]*B+a[2]*C


34.7 µs ± 5.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%%timeit
torch.einsum('kij,k->ij',H,a)

35.3 µs ± 9.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### GPU

In [9]:
a.to(torch. device('cuda'))
A.to(torch. device('cuda'))
B.to(torch. device('cuda'))
C.to(torch. device('cuda'))
H.to(torch. device('cuda'))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]], device='cuda:0')

In [13]:
%%timeit
a[0]*A+a[1]*B+a[2]*C

20 µs ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%%timeit
torch.einsum('kij,k->ij',H,a)

29.8 µs ± 6.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Multi output Channel
3 input to 4 output

In [15]:
b=torch.stack([a,a,a,a])
b.to(torch. device('cuda'))

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')

In [16]:
torch.einsum('hij,kh->kij',H,b)

tensor([[[17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.]],

        [[17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.]],

        [[17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.]],

        [[17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.],
         [17., 17., 17., 17., 17.]]])

### Batch
